#! /bin/bash
touch	/tmp/Chapter.xml
Chap=/tmp/Chapter.xml 

echo "<?xml version='1.0' encoding='utf-8' ?>" > $Chap
echo '<!DOCTYPE chapter PUBLIC "-//OASIS//DTD DocBook XML V4.5//EN" "http://www.oasis-open.org/docbook/xml/4.5/docbookx.dtd" '>>$Chap
echo '[<!ENTITY % BOOK_ENTITIES SYSTEM "virtualizacion.ent"> %BOOK_ENTITIES;]>' >> $Chap

#Build the chapter id 
echo '<chapter id="Cap_Virtualizacion">' >> $Chap
	echo -e '\t<title>Virtualización</title>' >> $Chap
	echo -e '\t<section id="Sec_Servicio">' >> $Chap
		echo -e '\t\t<title>Servicio de virtualizacion</title>' >>$Chap
	
		libvirtd=`ps awx | grep 'libvirtd' |grep -v grep|wc -l`
		if [ $libvirtd == 0 ]; 
			then
				echo -e '\t<para>' >> $Chap
				echo -e "El servicio de virtualización no esta activo" >> $Chap
				echo -e '\t</para>' >> $Chap
			else
				echo -e '\t<para>' >> $Chap
				echo "El servicio de virtualización esta activo" >> $Chap
				echo -e '\t</para>' >> $Chap

		fi	
	echo -e '\t</section>' >> $Chap

		if [ $libvirtd != 0 ];	#si el servicio de virtualizacion esta activo muestra las siguientes secciones
			then
				echo -e '\t<section id="Sec_M-Total">' >> $Chap
					echo -e '\t\t<title>Total de Maquinas</title>' >>$Chap
						TOTmaq=`virsh list --all|wc -l`
						echo -e "\t<para>Total de maquinas: \t</para>" >> $Chap
					## Imprime el total de maquinas
							echo -e "\t<para>" >> $Chap
						echo -e $TOTmaq | awk '{ $2 = $1-3 ;print $2}' >> $Chap
						echo -e "\t</para>" >> $Chap
					
					## Imprime la lista de maquinas:
						if [ $TOTmaq != 3 ];
							then
								echo -e "\t<para>Lista de Maquinas:</para>" >> $Chap
					 			#echo -e "\t<para>" >> $Chap
								#lista2=$(virsh list --all |grep -v "^$\|State\|Estado\|---"|awk '{ print "\t<listitem>\t<para>" $2 "&#9; " $3 "</para>\t</listitem>" }')
								#echo -e "<orderedlist>"$lista2"</orderedlist>" >> $Chap
								#echo -e "\t</para>" >> $Chap
								listaaux=$(virsh list --all |grep -v "^$\|State\|Estado\|---"|awk '{print $2}')
								arreglo=($listaaux)
								for (( i=0; i<$TOTmaq-3 ; i++))
									do
										echo -e "<para> "---------" </para>" >>$Chap
										echo -e "<para>" >> $Chap
										echo -e `virsh dominfo ${arreglo[ $i ]}|awk ' /Name/ {print $1 " " $2}'` >> $Chap
										echo -e "</para>" >>$Chap
										echo -e "<para>" >> $Chap
										echo -e `virsh dominfo ${arreglo[ $i ]}|awk ' /State/ {print $1 " " $2 " "$3}'` >> $Chap
										echo -e "</para>" >>$Chap
										echo -e "<para>" >> $Chap
										echo -e `virsh dominfo ${arreglo[ $i ]}|awk ' /Used memory/ {printf "%s %s\t%s %s", $1,$2,$3,$4}'` >> $Chap
										echo -e "</para>" >>$Chap
										echo -e "<para>" >> $Chap
										echo -e `virsh dominfo ${arreglo[ $i ]}|awk ' /OS Type/ {print $1 " " $2 " " $3}'` >> $Chap
										echo -e "</para>" >>$Chap
										echo -e "<para>" >> $Chap
										echo -e `virsh dominfo ${arreglo[ $i ]}|awk ' /CPU\(s\)/ {print $1 " " $2}'` >> $Chap
										echo -e "</para>" >>$Chap
										echo -e "<para>" >> $Chap
										echo -e `virsh dominfo ${arreglo[ $i ]}|awk ' /CPU time/ {print $1 " " $2 " " $3}'` >> $Chap
										echo -e "</para>" >>$Chap
									done
							fi

				echo -e '\t</section>' >> $Chap

				echo -e '\t<section id="Sec_M-Activ">' >> $Chap
					echo -e '\t\t<title>Maquinas Encendidas</title>' >>$Chap
						maqACT=`virsh list|grep "ejecutando\|running"|wc -l`
						echo -e "\t<para>Maquinas activas: \t</para>" >> $Chap
						echo -e "\t<para>$maqACT\t</para>" >> $Chap
						if [ $maqACT != 0 ];
							then
								echo -e "\t<para>Lista de Maquinas activas</para>" >> $Chap
								#echo -e "\t<para>" >> $Chap
								#lista=$(virsh list|grep "ejecutando\|running"|awk '{ print "\t<listitem>\t<para>" $2 "</para>\t</listitem>" }')
								#echo -e "<orderedlist>"$lista"</orderedlist>" >> $Chap
								#echo -e "\t</para>" >> $Chap
								listaaux=$(virsh list|grep "ejecutando\|running"|awk '{print $2}')
								arreglo=($listaaux)
								for (( i=0; i<$maqACT ; i++))
									do
										echo -e "<para> "---------" </para>" >>$Chap
										echo -e "<para>" >> $Chap
										echo -e `virsh dominfo ${arreglo[ $i ]}|awk ' /Name/ {print $1 " " $2}'` >> $Chap
										echo -e "</para>" >>$Chap
										echo -e "<para>" >> $Chap
										echo -e `virsh dominfo ${arreglo[ $i ]}|awk ' /Used memory/ {printf "%s %s\t%s %s", $1,$2,$3,$4}'` >> $Chap
										echo -e "</para>" >>$Chap
										echo -e "<para>" >> $Chap
										echo -e `virsh dominfo ${arreglo[ $i ]}|awk ' /OS Type/ {print $1 " " $2 " " $3}'` >> $Chap
										echo -e "</para>" >>$Chap
										echo -e "<para>" >> $Chap
										echo -e `virsh dominfo ${arreglo[ $i ]}|awk ' /CPU\(s\)/ {print $1 " " $2}'` >> $Chap
										echo -e "</para>" >>$Chap
										echo -e "<para>" >> $Chap
										echo -e `virsh dominfo ${arreglo[ $i ]}|awk ' /CPU time/ {print $1 " " $2 " " $3}'` >> $Chap
										echo -e "</para>" >>$Chap
									done
							fi
				echo -e '\t</section>' >> $Chap	
		fi
echo '</chapter>' >> $Chap

#
#cp /tmp/Chapter.xml /home/theme/Virtualizacion/en-US/|publican build --formats=html --langs=en-US
#
